# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  #排序组织
  - Name: Orderer
    Domain: orderer.com
    Specs:
      - Hostname: ord
      
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  #Admin组织
  - Name: Admin
    Domain: admin.com
    Template:
      Count: 1
    Users:
      Count: 2
  # ---------------------------------------------------------------------------
  #User组织    
  - Name: User
    Domain: user.com
    Template:
      Count: 2
    Users:
      Count: 3      
