# All elements in this file should depend on the docker-base.yaml
# Provided solo-base fabric network with:

# ca.org1.example.com
# ca.org2.example.com
# orderer.example.com
# peer0.org1.example.com
# peer1.org1.example.com
# peer0.org2.example.com
# peer1.org2.example.com
# cli

version: '2'  # v3 does not support 'extends' yet

services:
#=============================================================================
  ord.orderer.com:
    extends:
      file: docker-base.yaml
      service: orderer-base
    container_name: ord.orderer.com
    ports:
      - "7050:7050"
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./crypto-config/ordererOrganizations/orderer.com/orderers/ord.orderer.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/orderer.com/orderers/ord.orderer.com/tls/:/var/hyperledger/orderer/tls

#=============================================================================
  peer0.admin.com:
    extends:
      file: docker-base.yaml
      service: peer-base
    container_name: peer0.admin.com
    environment:
      - CORE_PEER_ID=peer0.admin.com
      - CORE_PEER_ADDRESS=peer0.admin.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.admin.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.admin.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.admin.com:7051
      - CORE_PEER_LOCALMSPID=AdminMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0.admin.couchdb:5984
    volumes:
      - /var/hyperledger/peer0.admin.com:/var/hyperledger/production
      - ./crypto-config/peerOrganizations/admin.com/peers/peer0.admin.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/admin.com/peers/peer0.admin.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start --peer-chaincodedev=true -o ord.orderer.com:7050
    ports:
      - "7051:7051"
      - "7052:7052"
      - "7053:7053"
    depends_on:
      - ord.orderer.com
      - peer0.admin.couchdb

  peer0.user.com:
    extends:
      file: docker-base.yaml
      service: peer-base
    container_name: peer0.user.com
    environment:
      - CORE_PEER_ID=peer0.user.com
      - CORE_PEER_ADDRESS=peer0.user.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.user.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.user.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.user.com:7051
      - CORE_PEER_LOCALMSPID=UserMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0.user.couchdb:5984
    volumes:
      - /var/hyperledger/peer0.user.com:/var/hyperledger/production
      - ./crypto-config/peerOrganizations/user.com/peers/peer0.user.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/user.com/peers/peer0.user.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start --peer-chaincodedev=true -o ord.orderer.com:7050
    ports:
      - "8051:7051"
      - "8052:7052"
      - "8053:7053"
    depends_on:
      - ord.orderer.com
      - peer0.user.couchdb      
      
  peer1.user.com:
    extends:
      file: docker-base.yaml
      service: peer-base
    container_name: peer1.user.com
    environment:
      - CORE_PEER_ID=peer1.user.com
      - CORE_PEER_ADDRESS=peer1.user.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.user.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.user.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.user.com:7051
      - CORE_PEER_LOCALMSPID=UserMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1.user.couchdb:5984
    volumes:
      - /var/hyperledger/peer1.user.com:/var/hyperledger/production
      - ./crypto-config/peerOrganizations/user.com/peers/peer1.user.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/user.com/peers/peer1.user.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start --peer-chaincodedev=true -o ord.orderer.com:7050
    ports:
      - "9051:7051"
      - "9052:7052"
      - "9053:7053"
    depends_on:
      - ord.orderer.com
      - peer1.user.couchdb
      
#==============================================================================      
  peer0.admin.couchdb:
    extends:
      file: docker-base.yaml
      service: couchdb-base
    container_name: peer0.admin.couchdb
    volumes:
      - /var/hyperledger/peer0.admin.couchdb:/opt/couchdb/data
    ports:
      - "5984:5984"
      
  peer0.user.couchdb:
    extends:
      file: docker-base.yaml
      service: couchdb-base
    container_name: peer0.user.couchdb
    volumes:
      - /var/hyperledger/peer0.user.couchdb:/opt/couchdb/data
    ports:
      - "6984:5984"  
      
  peer1.user.couchdb:
    extends:
      file: docker-base.yaml
      service: couchdb-base
    container_name: peer1.user.couchdb
    volumes:
      - /var/hyperledger/peer1.user.couchdb:/opt/couchdb/data
    ports:
      - "7984:5984"  
      
#=============================================================================
  cli: 
    image: hyperledger/fabric-tools
    container_name: cli
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ID=fabric-cli
      - CORE_PEER_ADDRESS=peer0.admin.com:7051
      - CORE_PEER_LOCALMSPID=AdminMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/zhangjenner/chaincode/stock/src/crypto/peerOrganizations/admin.com/users/Admin@admin.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/zhangjenner/chaincode/stock/src/crypto/peerOrganizations/admin.com/tlsca/tlsca.admin.com-cert.pem
    working_dir: /opt/gopath/src/github.com/zhangjenner/chaincode/stock/src
    volumes:
        - /home/zhangjenner/workspace/gopath/src/github.com/pkg:/opt/gopath/src/github.com/pkg
        - /home/zhangjenner/workspace/gopath/src/github.com/golang:/opt/gopath/src/github.com/golang
        - /home/zhangjenner/workspace/gopath/src/github.com/hyperledger:/opt/gopath/src/github.com/hyperledger
        - /home/zhangjenner/workspace/gopath/src/github.com/zhangjenner:/opt/gopath/src/github.com/zhangjenner
        - ./script.sh:/opt/gopath/src/github.com/zhangjenner/chaincode/stock/src/script.sh
        - ./crypto-config:/opt/gopath/src/github.com/zhangjenner/chaincode/stock/src/crypto
        - ./channel-artifacts:/opt/gopath/src/github.com/zhangjenner/chaincode/stock/src/artifacts        
        
#=============================================================================
  cc1:    
    image: hyperledger/fabric-ccenv
    container_name: cc1
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cc1
      - CORE_CHAINCODE_ID_NAME=stockcc:1.0
      - CORE_PEER_ADDRESS=peer0.admin.com:7052
      - CORE_PEER_LOCALMSPID=AdminMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/admin.com/peers/peer0.admin.com/msp
    working_dir: /opt/gopath/src/github.com/zhangjenner/chaincode/stock/bin
    volumes:
        - /home/zhangjenner/workspace/gopath/bin:/opt/gopath/src/github.com/zhangjenner/chaincode/stock/bin
        - /home/zhangjenner/workspace/gopath/src/github.com/pkg:/opt/gopath/src/github.com/pkg
        - /home/zhangjenner/workspace/gopath/src/github.com/golang:/opt/gopath/src/github.com/golang
        - /home/zhangjenner/workspace/gopath/src/github.com/hyperledger:/opt/gopath/src/github.com/hyperledger
        - /home/zhangjenner/workspace/gopath/src/github.com/zhangjenner:/opt/gopath/src/github.com/zhangjenner
        - ./crypto-config:/opt/gopath/src/crypto
    depends_on:
      - ord.orderer.com
      - peer0.admin.com
      
  cc2:    
    image: hyperledger/fabric-ccenv
    container_name: cc2
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cc2
      - CORE_CHAINCODE_ID_NAME=stockcc:1.0
      - CORE_PEER_ADDRESS=peer0.user.com:7052
      - CORE_PEER_LOCALMSPID=AdminMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/user.com/peers/peer0.user.com/msp
    working_dir: /opt/gopath/src/github.com/zhangjenner/chaincode/stock/bin
    volumes:
        - /home/zhangjenner/workspace/gopath/bin:/opt/gopath/src/github.com/zhangjenner/chaincode/stock/bin
        - /home/zhangjenner/workspace/gopath/src/github.com/pkg:/opt/gopath/src/github.com/pkg
        - /home/zhangjenner/workspace/gopath/src/github.com/golang:/opt/gopath/src/github.com/golang
        - /home/zhangjenner/workspace/gopath/src/github.com/hyperledger:/opt/gopath/src/github.com/hyperledger
        - /home/zhangjenner/workspace/gopath/src/github.com/zhangjenner:/opt/gopath/src/github.com/zhangjenner
        - ./crypto-config:/opt/gopath/src/crypto
    depends_on:
      - ord.orderer.com
      - peer0.user.com
      
  cc3:    
    image: hyperledger/fabric-ccenv
    container_name: cc3
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cc3
      - CORE_CHAINCODE_ID_NAME=stockcc:1.0
      - CORE_PEER_ADDRESS=peer1.user.com:7052
      - CORE_PEER_LOCALMSPID=AdminMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/user.com/peers/peer1.user.com/msp
    working_dir: /opt/gopath/src/github.com/zhangjenner/chaincode/stock/bin
    volumes:
        - /home/zhangjenner/workspace/gopath/bin:/opt/gopath/src/github.com/zhangjenner/chaincode/stock/bin
        - /home/zhangjenner/workspace/gopath/src/github.com/pkg:/opt/gopath/src/github.com/pkg
        - /home/zhangjenner/workspace/gopath/src/github.com/golang:/opt/gopath/src/github.com/golang
        - /home/zhangjenner/workspace/gopath/src/github.com/hyperledger:/opt/gopath/src/github.com/hyperledger
        - /home/zhangjenner/workspace/gopath/src/github.com/zhangjenner:/opt/gopath/src/github.com/zhangjenner
        - ./crypto-config:/opt/gopath/src/crypto
    depends_on:
      - ord.orderer.com
      - peer1.user.com
      
      