# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  #排序组织
  - Name: Orderer
    Domain: orderer.com
    Specs:
      - Hostname: ord
      
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  #A银行组织    
  - Name: BankA
    Domain: banka.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  #B银行组织    
  - Name: BankB
    Domain: bankb.com
    Template:
      Count: 1
    Users:
      Count: 1      
